import Link from "next/link";
import { PatientMatchReview } from "@/components/patients/PatientMatchReview";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusPill } from "@/components/StatusPill";
import { requireStaffContext } from "@/lib/auth/server";
import { canReviewPatientIdentity } from "@/lib/auth/roles";
import { createClient } from "@/lib/supabase/server";
import { shortDate } from "@/lib/format";

export default async function PatientsPage(){const staff=await requireStaffContext();const supabase=await createClient();const[{data:patients},{data:candidates}]=await Promise.all([supabase.from("crm_patient").select("id,display_name,account_ref,file_ref,date_of_birth,primary_phone,primary_email,status,data_quality_status,source_system,source_last_seen_at").eq("practice_id",staff.practiceId).order("display_name").limit(500),supabase.from("crm_patient_match_candidate").select("id,patient_a_id,patient_b_id,match_score,match_reasons,status").eq("practice_id",staff.practiceId).order("match_score",{ascending:false}).limit(100)]);return <div className="space-y-6"><SectionHeader title="Patients" body="CRM patient context is source-linked and auditable. Matching candidates are reviewed manually; no automatic merging is allowed."/><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Account</th><th className="px-4 py-3">DOB</th><th className="px-4 py-3">Quality</th></tr></thead><tbody>{(patients||[]).map((p:any)=><tr key={p.id} className="border-t border-stone-100"><td className="px-4 py-3"><Link href={`/patients/${p.id}`} className="font-medium text-[#4a1f3e] hover:underline">{p.display_name}</Link><p className="mt-1 text-xs text-stone-500">{p.primary_phone||p.primary_email||"No primary contact"}</p></td><td className="px-4 py-3 text-xs text-stone-600">{p.source_system}</td><td className="px-4 py-3 text-xs text-stone-600">{p.account_ref||"—"}<br/>{p.file_ref?`File ${p.file_ref}`:""}</td><td className="px-4 py-3 text-xs text-stone-600">{shortDate(p.date_of_birth)}</td><td className="px-4 py-3"><StatusPill value={p.data_quality_status}/></td></tr>)}</tbody></table></div>{!(patients||[]).length?<p className="p-6 text-sm text-stone-500">No patients have been promoted into PracticeCtrl yet. A validated VeriClaim import can create source-linked patient records without changing VeriClaim itself.</p>:null}</div>{canReviewPatientIdentity(staff.role)?<PatientMatchReview practiceId={staff.practiceId} userId={staff.userId} candidates={(candidates||[]) as any}/>:null}</div>}
