"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Patient={id:string;display_name:string};
type Practitioner={id:string;display_name:string;user_id:string|null;profession:string|null;speciality:string|null;default_location_id:string|null};
type AppointmentType={id:string;name:string;duration_minutes:number;encounter_type:string};
type Location={id:string;name:string;location_type:string};
type Request={id:string;patient_id:string|null;requester_name:string;requested_service:string|null;preferred_date:string|null;preferred_time:string|null;status:string};
type Waitlist={id:string;patient_id:string;appointment_type_id:string|null;practitioner_id:string|null;preferred_from:string|null;preferred_to:string|null;priority:number;status:string;notes:string|null};
type Appointment={id:string;appointment_number:string;patient_id:string;practitioner_id:string;appointment_type_id:string;location_id:string|null;starts_at:string;ends_at:string;status:string;reason:string|null;encounter_id:string|null;registration_status?:string;registration_verified_at?:string|null};

const NEXT:Record<string,string[]>={booked:["confirmed","checked_in","cancelled","no_show"],confirmed:["checked_in","cancelled","no_show"],checked_in:["in_progress","cancelled"],in_progress:["completed"]};

export function AppointmentWorkspace({practiceId,patients,practitioners,types,locations,requests,appointments,waitlist,canSchedule,userId,role}:{practiceId:string;patients:Patient[];practitioners:Practitioner[];types:AppointmentType[];locations:Location[];requests:Request[];appointments:Appointment[];waitlist:Waitlist[];canSchedule:boolean;userId:string;role:string}){
 const supabase=useMemo(()=>createClient(),[]); const[busy,setBusy]=useState(false); const[msg,setMsg]=useState<string|null>(null);
 async function book(fd:FormData){setBusy(true);setMsg(null);const local=String(fd.get("startsAt")||"");const starts=local?new Date(local).toISOString():"";const{data,error}=await supabase.rpc("create_practice_appointment",{p_practice_id:practiceId,p_patient_id:String(fd.get("patientId")),p_practitioner_id:String(fd.get("practitionerId")),p_appointment_type_id:String(fd.get("typeId")),p_starts_at:starts,p_location_id:String(fd.get("locationId")||"")||null,p_booking_source:String(fd.get("requestId")||"")?"request":"internal",p_reason:String(fd.get("reason")||"")||null,p_notes:String(fd.get("notes")||"")||null,p_appointment_request_id:String(fd.get("requestId")||"")||null});setBusy(false);if(error)setMsg(error.message);else{setMsg(`Appointment created: ${data}`);window.location.reload();}}
 async function status(id:string,next:string){let reason:string|null=null;if(next==="cancelled")reason=window.prompt("Cancellation reason")||"";if(next==="cancelled"&&!String(reason||"").trim()){setMsg("A cancellation reason is required.");return;}setBusy(true);setMsg(null);const{error}=await supabase.rpc("update_practice_appointment_status",{p_appointment_id:id,p_status:next,p_reason:reason});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
 async function addWaitlist(fd:FormData){setBusy(true);setMsg(null);const{error}=await supabase.from("appointment_waitlist").insert({practice_id:practiceId,patient_id:String(fd.get("patientId")),appointment_type_id:String(fd.get("typeId")||"")||null,practitioner_id:String(fd.get("practitionerId")||"")||null,preferred_from:String(fd.get("preferredFrom")||"")||null,preferred_to:String(fd.get("preferredTo")||"")||null,priority:Number(fd.get("priority")||3),notes:String(fd.get("notes")||"")||null,created_by:userId});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
 async function closeWaitlist(id:string){setBusy(true);const{error}=await supabase.from("appointment_waitlist").update({status:"closed",updated_at:new Date().toISOString()}).eq("id",id);setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
 async function reschedule(id:string){const value=window.prompt("New date/time (YYYY-MM-DDTHH:MM)");if(!value)return;const reason=window.prompt("Reason for rescheduling (optional)")||null;setBusy(true);setMsg(null);const{error}=await supabase.rpc("reschedule_practice_appointment",{p_appointment_id:id,p_starts_at:new Date(value).toISOString(),p_location_id:null,p_reason:reason});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
 function allowedNext(a:Appointment){const all=NEXT[a.status]||[];if(["practice_manager","clinical_admin","system_admin"].includes(role))return all;if(role==="reception")return all.filter(x=>["confirmed","checked_in","cancelled","no_show"].includes(x));const practitioner=practitioners.find(p=>p.id===a.practitioner_id);if(role==="practitioner"&&practitioner?.user_id===userId)return all.filter(x=>["in_progress","completed"].includes(x));return [];}
 const ready=patients.length>0&&practitioners.length>0&&types.length>0;
 return <div className="space-y-4">
  {canSchedule?<form action={book} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-[#4a1f3e]">Book appointment</h3><p className="mt-1 text-sm text-stone-500">One booking becomes the operational anchor for check-in and the clinical encounter.</p></div>{!ready?<span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-800">Setup required</span>:null}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><select name="patientId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><select name="practitionerId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Practitioner</option>{practitioners.map(p=><option key={p.id} value={p.id}>{p.display_name}{p.speciality?` · ${p.speciality}`:""}</option>)}</select><select name="typeId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Appointment type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name} · {t.duration_minutes} min</option>)}</select><input name="startsAt" type="datetime-local" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><select name="locationId" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">No room / location</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select name="requestId" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Direct booking</option>{requests.filter(r=>r.status!=="Booked in PracticeCtrl").map(r=><option key={r.id} value={r.id}>Request · {r.requester_name}{r.preferred_date?` · ${r.preferred_date}`:""}</option>)}</select><input name="reason" placeholder="Reason / service" className="rounded-xl border border-stone-300 px-3 py-2 text-sm md:col-span-2"/><input name="notes" placeholder="Scheduling note (optional)" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div><button disabled={busy||!ready} className="mt-4 rounded-xl bg-[#4a1f3e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Create appointment</button></form>:null}
  {canSchedule?<section className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><form action={addWaitlist} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Waitlist</h3><p className="mt-1 text-sm text-stone-500">Capture patients who can take an earlier or newly opened slot.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><select name="patientId" required className="rounded-lg border border-stone-300 px-3 py-2 text-sm"><option value="">Patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><select name="typeId" className="rounded-lg border border-stone-300 px-3 py-2 text-sm"><option value="">Any appointment type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select name="practitionerId" className="rounded-lg border border-stone-300 px-3 py-2 text-sm"><option value="">Any practitioner</option>{practitioners.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><select name="priority" defaultValue="3" className="rounded-lg border border-stone-300 px-3 py-2 text-sm"><option value="1">Priority 1</option><option value="2">Priority 2</option><option value="3">Priority 3</option><option value="4">Priority 4</option><option value="5">Priority 5</option></select><input name="preferredFrom" type="date" className="rounded-lg border border-stone-300 px-3 py-2 text-sm"/><input name="preferredTo" type="date" className="rounded-lg border border-stone-300 px-3 py-2 text-sm"/><input name="notes" placeholder="Availability note" className="rounded-lg border border-stone-300 px-3 py-2 text-sm sm:col-span-2"/></div><button disabled={busy} className="mt-3 rounded-lg border border-stone-300 px-3 py-2 text-sm">Add to waitlist</button></form><div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Waiting patients</h3><div className="mt-3 grid gap-2">{waitlist.filter(w=>w.status!=="closed").slice(0,12).map(w=><div key={w.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-stone-200 p-3"><div><p className="text-sm font-medium">{patients.find(p=>p.id===w.patient_id)?.display_name||"Patient"}</p><p className="text-xs text-stone-500">Priority {w.priority}{w.preferred_from?` · from ${w.preferred_from}`:""}{w.preferred_to?` to ${w.preferred_to}`:""}</p></div><button type="button" onClick={()=>closeWaitlist(w.id)} className="rounded-lg border border-stone-300 px-2.5 py-1 text-xs">Close</button></div>)}{!waitlist.filter(w=>w.status!=="closed").length?<p className="text-sm text-stone-500">No active waitlist entries.</p>:null}</div></div></section>:null}
  <div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs text-stone-500"><tr><th className="px-4 py-3">Appointment</th><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Practitioner</th><th className="px-4 py-3">When</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Registration</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id} className="border-t border-stone-100 align-top"><td className="px-4 py-3"><p className="font-medium">{a.appointment_number}</p><p className="mt-1 text-xs text-stone-500">{types.find(t=>t.id===a.appointment_type_id)?.name||"Appointment"}{a.encounter_id?" · encounter linked":""}</p></td><td className="px-4 py-3">{patients.find(p=>p.id===a.patient_id)?.display_name||"Patient"}</td><td className="px-4 py-3">{practitioners.find(p=>p.id===a.practitioner_id)?.display_name||"Practitioner"}</td><td className="px-4 py-3 text-xs text-stone-600">{new Date(a.starts_at).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short"})}</td><td className="px-4 py-3"><span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-medium text-stone-700">{a.status.replaceAll("_"," ")}</span></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${a.registration_status==="verified"?"bg-emerald-50 text-emerald-800":a.registration_status==="submitted"?"bg-amber-50 text-amber-800":"bg-stone-100 text-stone-600"}`}>{(a.registration_status||"not_required").replaceAll("_"," ")}</span></td><td className="px-4 py-3"><div className="flex min-w-48 flex-wrap gap-1.5">{allowedNext(a).map(n=><button key={n} disabled={busy} onClick={()=>status(a.id,n)} className="rounded-lg border border-stone-300 px-2 py-1 text-xs hover:bg-stone-50">{n.replaceAll("_"," ")}</button>)}{canSchedule&&["booked","confirmed"].includes(a.status)?<button disabled={busy} onClick={()=>reschedule(a.id)} className="rounded-lg border border-stone-300 px-2 py-1 text-xs hover:bg-stone-50">reschedule</button>:null}</div></td></tr>)}</tbody></table></div>{!appointments.length?<p className="p-6 text-sm text-stone-500">No appointments in the current diary window.</p>:null}</div>
  {msg?<p className="rounded-xl bg-stone-100 p-3 text-sm text-stone-700">{msg}</p>:null}
 </div>;
}
