"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function PatientMembershipForm({ patientId, practiceId }: { patientId:string; practiceId:string }) {
  const supabase=createClient(); const [msg,setMsg]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function submit(formData:FormData){setBusy(true);setMsg(null);const {data,error}=await supabase.functions.invoke("practicectrl-patient-membership",{body:{patientId,schemeName:String(formData.get("schemeName")||""),optionName:String(formData.get("optionName")||""),memberNumber:String(formData.get("memberNumber")||""),dependantCode:String(formData.get("dependantCode")||"")},headers:{"x-practicectrl-practice-id":practiceId}});setBusy(false);if(error)setMsg(error.message);else if(data?.error)setMsg(data.error);else{setMsg("Scheme membership stored securely. Full member number is encrypted and not returned to the browser.");window.location.reload();}}
  return <form action={submit} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Add medical-scheme membership</h3><p className="mt-1 text-sm text-stone-500">The full member number is stored encrypted in Supabase Vault; only a masked value is shown afterwards.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="schemeName" required placeholder="Scheme name" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><input name="optionName" placeholder="Option / plan" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><input name="memberNumber" required autoComplete="off" placeholder="Member number" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><input name="dependantCode" placeholder="Dependant code" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div><button disabled={busy} className="mt-4 rounded-xl bg-[#4a1f3e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Store securely</button>{msg?<p className="mt-3 text-sm text-stone-600">{msg}</p>:null}</form>;
}
