"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function PatientMatchReview({ practiceId, candidates, userId }: { practiceId:string; userId:string; candidates:Array<{id:string;patient_a_id:string;patient_b_id:string;match_score:number;match_reasons:string[];status:string}> }) {
  const supabase=createClient(); const [msg,setMsg]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function refresh(){setBusy(true);const {data,error}=await supabase.rpc("refresh_crm_match_candidates",{p_practice_id:practiceId});setBusy(false);if(error)setMsg(error.message);else{setMsg(`${data} new candidate pair(s) added.`);window.location.reload();}}
  async function review(id:string,status:"same_person"|"not_same_person"|"deferred"){setBusy(true);const {error}=await supabase.from("crm_patient_match_candidate").update({status,reviewed_by:userId,reviewed_at:new Date().toISOString(),review_note:status==="same_person"?"Reviewed as the same person; no automatic merge performed.":"Identity review completed."}).eq("id",id);setBusy(false);if(error)setMsg(error.message);else{setMsg("Identity review saved. No patient records were merged.");window.location.reload();}}
  return <div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-[#4a1f3e]">Duplicate-patient review</h3><p className="mt-1 text-sm text-stone-500">Candidate detection never merges patients automatically.</p></div><button type="button" onClick={refresh} disabled={busy} className="rounded-xl border border-stone-300 px-3 py-2 text-sm">Refresh candidates</button></div><div className="mt-4 grid gap-3">{candidates.filter(c=>c.status==="pending").slice(0,8).map(c=><div key={c.id} className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-medium">Pair {c.patient_a_id.slice(0,8)} / {c.patient_b_id.slice(0,8)} · {Math.round(Number(c.match_score)*100)}%</p><p className="text-xs text-stone-500">{c.match_reasons.join(" · ")||"Similarity candidate"}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>review(c.id,"same_person")} className="rounded-lg border px-2.5 py-1.5 text-xs">Same person</button><button type="button" disabled={busy} onClick={()=>review(c.id,"not_same_person")} className="rounded-lg border px-2.5 py-1.5 text-xs">Not same</button><button type="button" disabled={busy} onClick={()=>review(c.id,"deferred")} className="rounded-lg border px-2.5 py-1.5 text-xs">Defer</button></div></div></div>)}{!candidates.some(c=>c.status==="pending")?<p className="text-sm text-stone-500">No pending identity candidates.</p>:null}</div>{msg?<p className="mt-3 text-sm text-stone-600">{msg}</p>:null}</div>;
}
