"use client";
import { FormEvent, useMemo, useState } from "react";
import { MetricCard } from "@/components/MetricCard";
import { WorkItemActions } from "@/components/operations/WorkItemActions";
import { createClient } from "@/lib/supabase/client";
import { money, shortDate, shortDateTime } from "@/lib/format";
import type { StaffRole } from "@/lib/auth/roles";

type Row={id:string;workflow:any;source:any;economics:any;payer:any;patient:any;operations:any;collection:any;communication:any};
function label(v:string|null|undefined){return (v||"—").replaceAll("_"," ");}

function ActionPanel({row,canAct}:{row:Row;canAct:boolean}){
  const supabase=useMemo(()=>createClient(),[]); const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<string|null>(null);
  async function action(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canAct)return;const fd=new FormData(e.currentTarget);setBusy(true);setMsg(null);const type=String(fd.get("action"));const raw=String(fd.get("amount")||"").trim();const amount=raw?Number(raw):null;const note=String(fd.get("note")||"").trim()||null;const ref=String(fd.get("reference")||"").trim()||null;const{error}=await supabase.rpc("record_revenue_recovery_action",{p_workflow_id:row.id,p_action_type:type,p_amount:amount,p_note:note,p_external_reference:ref});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
  async function liability(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);setMsg(null);const{error}=await supabase.rpc("resolve_revenue_liability",{p_case_id:row.collection.collection_case_id,p_liability_status:String(fd.get("liability")),p_suppress_automation:String(fd.get("contact"))!=="allow",p_note:String(fd.get("note")||"")||null});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
  async function draft(){setBusy(true);setMsg(null);const{error}=await supabase.rpc("prepare_revenue_recovery_patient_draft",{p_workflow_id:row.id,p_channel:"email"});setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
  if(!canAct)return null;
  const coding=row.workflow.type==="coding_review";
  return <div className="mt-4 grid gap-3 border-t border-stone-100 pt-4">
    {row.workflow.type==="patient_collection"&&row.collection.collection_case_id?<form onSubmit={liability} className="grid gap-2 md:grid-cols-[180px_220px_1fr_auto]"><select name="liability" defaultValue={row.collection.liability_status||"unresolved"} className="rounded-lg border border-stone-300 px-2 py-2 text-xs"><option value="unresolved">Unresolved</option><option value="scheme_verified">Scheme liability</option><option value="patient_verified">Patient verified</option><option value="split_verified">Split verified</option><option value="credit">Credit</option><option value="zero_balance">Zero balance</option></select><select name="contact" defaultValue={row.collection.suppressed?"suppress":"allow"} className="rounded-lg border border-stone-300 px-2 py-2 text-xs"><option value="suppress">Keep contact suppressed</option><option value="allow">Allow controlled contact</option></select><input name="note" required placeholder="Liability evidence / note" className="rounded-lg border border-stone-300 px-2 py-2 text-xs"/><button disabled={busy} className="rounded-lg border border-stone-300 px-3 py-2 text-xs font-medium">Save liability gate</button></form>:null}
    <form onSubmit={action} className="grid gap-2 md:grid-cols-[180px_120px_1fr_180px_auto]"><select name="action" className="rounded-lg border border-stone-300 px-2 py-2 text-xs"><option value="reviewed">Reviewed / ready</option><option value="started">Start recovery</option>{coding?<option value="note">Coding review note</option>:<><option value="resubmitted">Claim resubmitted</option><option value="appealed">Appeal lodged</option><option value="payer_contacted">Payer contacted</option><option value="patient_contacted">Patient contacted</option><option value="waiting_payer">Waiting payer</option><option value="waiting_patient">Waiting patient</option></>}<option value="payment_received">Record recovery</option><option value="mark_non_recoverable">Mark non-recoverable</option><option value="written_off">Write off</option><option value="note">Add note</option><option value="close">Close</option></select><input name="amount" type="number" min="0" step="0.01" placeholder="Amount" className="rounded-lg border border-stone-300 px-2 py-2 text-xs"/><input name="note" placeholder="Action note / evidence" className="rounded-lg border border-stone-300 px-2 py-2 text-xs"/><input name="reference" placeholder="External ref" className="rounded-lg border border-stone-300 px-2 py-2 text-xs"/><button disabled={busy} className="rounded-lg bg-[#4a1f3e] px-3 py-2 text-xs font-medium text-white disabled:opacity-50">Record</button></form>
    {row.workflow.type==="patient_collection"&&row.collection.liability_status&&["patient_verified","split_verified"].includes(row.collection.liability_status)&&row.collection.suppressed===false?<div className="flex flex-wrap items-center gap-2"><button type="button" disabled={busy} onClick={draft} className="rounded-lg border border-stone-300 px-3 py-2 text-xs font-medium">Prepare consented email draft</button><span className="text-xs text-stone-500">Draft only. PracticeCtrl does not auto-send collection messages in v0.33.</span></div>:null}
    {msg?<p className="text-xs text-rose-700">{msg}</p>:null}
  </div>;
}

export function RecoveryOrchestrationWorkspace({practiceId,role,canManage,data}:{practiceId:string;role:StaffRole;canManage:boolean;data:any}){
  const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<string|null>(null);const metrics=data?.metrics||{};const rows=(data?.rows||[]) as Row[];const canAct=canManage||role==="coder";
  async function sync(){setBusy(true);setMsg(null);const{data:r,error}=await supabase.rpc("refresh_revenue_recovery_workflows",{p_practice_id:practiceId});setBusy(false);if(error)setMsg(error.message);else{setMsg(`Synchronised ${r?.leakage_cases_synchronised??0} leakage case(s).`);window.location.reload();}}
  return <div className="space-y-6">
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><MetricCard label="Open workflows" value={String(metrics.open_workflows||0)} note={`${metrics.overdue||0} overdue`}/><MetricCard label="Recoverable open value" value={money(metrics.recoverable_open_value)} note="Recoverable / possibly recoverable"/><MetricCard label="Patient liability open" value={money(metrics.patient_liability_open)} note={`${metrics.patient_contact_ready||0} contact-ready · ${metrics.patient_contact_blocked||0} gated`}/><MetricCard label="Recovered value" value={money(metrics.recovered_value)} note="Recorded recovery events"/><MetricCard label="Claim deadlines" value={String(metrics.claim_deadline_7d||0)} note="Due in the next 7 days"/></section>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-stone-200 bg-white p-4 shadow-sm"><div><p className="font-medium text-[#4a1f3e]">Recovery controls</p><p className="mt-1 text-sm text-stone-600">Payer destinations are never inferred. Patient contact requires verified liability, an allowed billing preference and a consented contact point.</p></div>{canManage?<button type="button" disabled={busy} onClick={sync} className="rounded-xl border border-stone-300 px-4 py-2 text-sm font-medium disabled:opacity-50">{busy?"Synchronising…":"Sync leakage cases"}</button>:null}</div>
    {msg?<p className="rounded-xl border border-stone-200 bg-white p-3 text-sm text-stone-700">{msg}</p>:null}
    <section className="grid gap-4">{rows.map(row=><article key={row.id} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-semibold">{label(row.workflow.type)}</span><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-800">{label(row.workflow.priority)}</span><span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs">{label(row.workflow.status)}</span></div><h3 className="mt-3 font-semibold text-[#4a1f3e]">{row.payer.scheme_name||"Private / patient"}{row.payer.plan_name?` · ${row.payer.plan_name}`:""} · {row.economics.procedure_code||"No procedure"}</h3><p className="mt-1 text-sm text-stone-600">{label(row.source.leakage_category)} · {label(row.workflow.recoverability)} · confidence {label(row.source.leakage_confidence)}</p>{row.patient.patient_name?<p className="mt-1 text-xs text-stone-500">{row.patient.patient_name}</p>:null}</div><div className="text-left lg:text-right"><p className="text-2xl font-semibold text-[#4a1f3e]">{money(row.workflow.remaining_amount)}</p><p className="text-xs text-stone-500">remaining of {money(row.workflow.original_amount)} · recovered {money(row.workflow.recovered_amount)}</p></div></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs uppercase tracking-wide text-stone-500">Next action</p><p className="mt-1 text-sm">{row.source.recommended_next_action||"Review and classify the recovery path."}</p></div><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs uppercase tracking-wide text-stone-500">Deadline</p><p className="mt-1 text-sm">{row.workflow.claim_deadline?`Claim ${shortDate(row.workflow.claim_deadline)}`:row.workflow.recovery_deadline?`Recovery ${shortDate(row.workflow.recovery_deadline)}`:row.operations.due_at?shortDateTime(row.operations.due_at):"No external deadline recorded"}</p></div><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs uppercase tracking-wide text-stone-500">Operations</p><p className="mt-1 text-sm">{label(row.operations.status)} · {row.operations.owner_user_id?"assigned":"unassigned"}</p><div className="mt-2"><WorkItemActions id={row.operations.work_item_id} status={row.operations.status||"open"} owned={Boolean(row.operations.owner_user_id)}/></div></div><div className="rounded-xl bg-stone-50 p-3"><p className="text-xs uppercase tracking-wide text-stone-500">Communication</p><p className="mt-1 text-sm">{row.workflow.type==="patient_collection"?(row.collection.suppressed?"Suppressed pending liability/consent gate":row.communication.allowed?"Controlled draft allowed":"Contact not enabled"):"Internal recovery workflow"}</p>{row.communication.latest_message_id?<p className="mt-1 text-xs text-stone-500">Draft/message linked</p>:null}</div></div>
      <ActionPanel row={row} canAct={canAct}/>
    </article>)}{!rows.length?<div className="rounded-2xl border border-stone-200 bg-white p-6 text-sm text-stone-500 shadow-sm">No recovery workflows match this view. If Economics already contains open leakage cases, use “Sync leakage cases” to reconcile historical cases into the workbench.</div>:null}</section>
  </div>;
}
