"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function RevenueCaseActions({ cases }: { cases:Array<{id:string;account_ref:string|null;liability_status:string;suppress_automation:boolean}> }) {
  const supabase=createClient(); const [msg,setMsg]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function resolve(formData:FormData){setBusy(true);const {error}=await supabase.rpc("resolve_revenue_liability",{p_case_id:String(formData.get("caseId")),p_liability_status:String(formData.get("status")),p_suppress_automation:String(formData.get("allowContact"))!=="yes",p_note:String(formData.get("note")||"")||null});setBusy(false);if(error)setMsg(error.message);else{setMsg("Revenue liability review saved.");window.location.reload();}}
  if(!cases.length) return null;
  return <form action={resolve} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Resolve liability gate</h3><p className="mt-1 text-sm text-stone-500">No patient collection communication may be enabled while liability is unresolved.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><select name="caseId" className="rounded-xl border border-stone-300 px-3 py-2 text-sm">{cases.map(c=><option key={c.id} value={c.id}>{c.account_ref||c.id.slice(0,8)} · {c.liability_status}</option>)}</select><select name="status" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="unresolved">Unresolved</option><option value="scheme_verified">Scheme verified</option><option value="patient_verified">Patient verified</option><option value="split_verified">Split verified</option><option value="credit">Credit</option><option value="zero_balance">Zero balance</option></select><select name="allowContact" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="no">Keep communication suppressed</option><option value="yes">Allow controlled contact</option></select><input name="note" required placeholder="Review evidence / note" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div><button disabled={busy} className="mt-4 rounded-xl bg-[#4a1f3e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Save review</button>{msg?<p className="mt-3 text-sm text-stone-600">{msg}</p>:null}</form>;
}
