"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Patient={id:string;display_name:string};
type Template={id:string;name:string;category:string;clinical_data:boolean};

type Doc={id:string;title:string;status:string;clinical_data:boolean};

export function DocumentWorkspace({practiceId,userId,patients,templates,documents}:{practiceId:string;userId:string;patients:Patient[];templates:Template[];documents:Doc[]}){
  const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState<string|null>(null);
  async function createDocument(fd:FormData){setBusy(true);setMsg(null);const templateId=String(fd.get("templateId")||"")||null;const t=templates.find(x=>x.id===templateId);const{data,error}=await supabase.from("patient_document").insert({practice_id:practiceId,patient_id:String(fd.get("patientId"))||null,template_id:templateId,document_type:t?.category||String(fd.get("documentType")||"administrative"),title:String(fd.get("title")||"").trim(),clinical_data:Boolean(t?.clinical_data),status:"draft",content_json:{body:String(fd.get("body")||"")},created_by:userId}).select("id").single();setBusy(false);if(error)setMsg(error.message);else{setMsg(`Document draft created: ${data.id}`);window.location.reload();}}
  async function createForm(fd:FormData){setBusy(true);setMsg(null);const templateId=String(fd.get("templateId"));const t=templates.find(x=>x.id===templateId);if(!t){setBusy(false);setMsg("Choose a form template.");return;}const{data,error}=await supabase.from("form_response").insert({practice_id:practiceId,patient_id:String(fd.get("patientId")),template_id:templateId,clinical_data:t.clinical_data,status:"submitted",answers:{summary:String(fd.get("summary")||"")},created_by:userId,submitted_by:userId,submitted_at:new Date().toISOString()}).select("id").single();setBusy(false);if(error)setMsg(error.message);else{setMsg(`Form response recorded: ${data.id}`);window.location.reload();}}
  async function recordConsent(fd:FormData){setBusy(true);setMsg(null);const{data,error}=await supabase.from("patient_consent").insert({practice_id:practiceId,patient_id:String(fd.get("patientId")),consent_type:String(fd.get("consentType")||"").trim(),consent_scope:String(fd.get("scope")||"").trim()||null,status:"active",effective_from:String(fd.get("effectiveFrom")||"")||null,effective_to:String(fd.get("effectiveTo")||"")||null,recorded_by:userId}).select("id").single();setBusy(false);if(error)setMsg(error.message);else{setMsg(`Consent recorded: ${data.id}`);window.location.reload();}}
  async function markGenerated(id:string){setBusy(true);setMsg(null);const{error}=await supabase.from("patient_document").update({status:"generated",generated_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
  async function signDocument(id:string){setBusy(true);setMsg(null);const{error}=await supabase.from("patient_document").update({status:"signed",signed_by:userId,signed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",id);setBusy(false);if(error)setMsg(error.message);else window.location.reload();}
  return <div className="grid gap-4 xl:grid-cols-3">
    <form action={createDocument} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Create document draft</h3><div className="mt-4 grid gap-3"><select name="patientId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><select name="templateId" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">No template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input name="title" required placeholder="Document title" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><textarea name="body" placeholder="Draft content / structured source text" className="min-h-28 rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div><button disabled={busy} className="mt-4 rounded-xl bg-[#4a1f3e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Create draft</button></form>
    <form action={createForm} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Record form response</h3><div className="mt-4 grid gap-3"><select name="patientId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><select name="templateId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><textarea name="summary" required placeholder="Response / consent summary" className="min-h-28 rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div><button disabled={busy} className="mt-4 rounded-xl border border-stone-300 px-4 py-2 text-sm font-medium">Record response</button></form>
    <form action={recordConsent} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Record consent</h3><div className="mt-4 grid gap-3"><select name="patientId" required className="rounded-xl border border-stone-300 px-3 py-2 text-sm"><option value="">Patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><input name="consentType" required placeholder="POPIA / treatment / communication…" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><textarea name="scope" placeholder="Scope / limitations" className="min-h-20 rounded-xl border border-stone-300 px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-2"><input name="effectiveFrom" type="date" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><input name="effectiveTo" type="date" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/></div></div><button disabled={busy} className="mt-4 rounded-xl border border-stone-300 px-4 py-2 text-sm font-medium">Record consent</button></form>
    <div className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-3"><h3 className="font-semibold text-[#4a1f3e]">Document actions</h3><div className="mt-4 flex flex-wrap gap-2">{documents.filter(d=>d.status==="draft"||d.status==="generated").slice(0,20).map(d=><div key={d.id} className="flex items-center gap-2 rounded-xl border border-stone-200 p-2 text-sm"><span>{d.title} · {d.status}</span>{d.status==="draft"?<button disabled={busy} type="button" onClick={()=>markGenerated(d.id)} className="rounded-lg border border-stone-300 px-2.5 py-1 text-xs">Mark generated</button>:null}{d.status==="generated"?<button disabled={busy} type="button" onClick={()=>signDocument(d.id)} className="rounded-lg bg-[#4a1f3e] px-2.5 py-1 text-xs text-white">Sign</button>:null}</div>)}</div>{msg?<p className="mt-4 rounded-xl bg-stone-50 p-3 text-sm text-stone-700">{msg}</p>:null}</div>
  </div>;
}
