import { DocumentWorkspace } from "@/components/documents/DocumentWorkspace";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusPill } from "@/components/StatusPill";
import { requireStaffContext } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { shortDate, shortDateTime } from "@/lib/format";

export default async function DocumentsPage(){const staff=await requireStaffContext();const supabase=await createClient();const[{data:patients},{data:templates},{data:documents},{data:forms},{data:consents}]=await Promise.all([
  supabase.from("crm_patient").select("id,display_name").eq("practice_id",staff.practiceId).eq("status","active").order("display_name").limit(500),
  supabase.from("document_template").select("id,name,category,clinical_data,practice_id,status").in("status",["active","draft"]).order("name"),
  supabase.from("patient_document").select("id,patient_id,title,document_type,clinical_data,status,generated_at,signed_at,created_at").eq("practice_id",staff.practiceId).order("created_at",{ascending:false}).limit(100),
  supabase.from("form_response").select("id,patient_id,template_id,status,submitted_at,signed_at,created_at").eq("practice_id",staff.practiceId).order("created_at",{ascending:false}).limit(100),
  supabase.from("patient_consent").select("id,patient_id,consent_type,consent_scope,status,granted_at,effective_from,effective_to,withdrawn_at").eq("practice_id",staff.practiceId).order("granted_at",{ascending:false}).limit(100),
]);const patientMap=new Map((patients||[]).map((p:any)=>[p.id,p.display_name]));const templateMap=new Map((templates||[]).map((t:any)=>[t.id,t.name]));return <div className="space-y-6"><SectionHeader title="Forms & Documents" body="One governed document service for consent forms, referral letters, medical certificates, clinical reports and practice correspondence. Clinical-data documents use stricter access rules than administrative records."/><DocumentWorkspace practiceId={staff.practiceId} userId={staff.userId} patients={(patients||[]) as any} templates={(templates||[]) as any} documents={(documents||[]) as any}/><section className="grid gap-4 xl:grid-cols-3"><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Documents</h3><div className="mt-4 grid gap-3">{(documents||[]).slice(0,30).map((d:any)=><div key={d.id} className="rounded-xl border border-stone-200 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{d.title}</p><p className="text-xs text-stone-500">{patientMap.get(d.patient_id)||"No patient"} · {d.document_type}</p></div><StatusPill value={d.status}/></div><p className="mt-2 text-xs text-stone-500">{shortDateTime(d.signed_at||d.generated_at||d.created_at)}</p></div>)}{!(documents||[]).length?<p className="text-sm text-stone-500">No documents yet.</p>:null}</div></article><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Form responses</h3><div className="mt-4 grid gap-3">{(forms||[]).slice(0,30).map((f:any)=><div key={f.id} className="rounded-xl border border-stone-200 p-3"><p className="text-sm font-medium">{templateMap.get(f.template_id)||"Form response"}</p><p className="text-xs text-stone-500">{patientMap.get(f.patient_id)||"Patient"} · {shortDateTime(f.submitted_at||f.created_at)}</p><div className="mt-2"><StatusPill value={f.status}/></div></div>)}{!(forms||[]).length?<p className="text-sm text-stone-500">No form responses yet.</p>:null}</div></article><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Consent register</h3><div className="mt-4 grid gap-3">{(consents||[]).slice(0,30).map((c:any)=><div key={c.id} className="rounded-xl border border-stone-200 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium">{c.consent_type}</p><p className="text-xs text-stone-500">{patientMap.get(c.patient_id)||"Patient"} · granted {shortDate(c.granted_at)}</p></div><StatusPill value={c.status}/></div>{c.consent_scope?<p className="mt-2 text-xs text-stone-600">{c.consent_scope}</p>:null}</div>)}{!(consents||[]).length?<p className="text-sm text-stone-500">No consents recorded.</p>:null}</div></article></section></div>}
