import { AuthorisationWorkspace } from "@/components/authorisations/AuthorisationWorkspace";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusPill } from "@/components/StatusPill";
import { requireStaffContext } from "@/lib/auth/server";
import { createClient } from "@/lib/supabase/server";
import { money, shortDate } from "@/lib/format";

export default async function AuthorisationsPage(){const staff=await requireStaffContext();const supabase=await createClient();const[{data:patients},{data:memberships},{data:encounters},{data:authorisations}]=await Promise.all([
  supabase.from("crm_patient").select("id,display_name").eq("practice_id",staff.practiceId).eq("status","active").order("display_name").limit(500),
  supabase.from("crm_patient_scheme_membership").select("id,patient_id,scheme_name_snapshot,option_name_snapshot,membership_status").eq("practice_id",staff.practiceId).order("created_at",{ascending:false}).limit(1000),
  supabase.from("practice_encounter").select("id,patient_id,service_date,encounter_type").eq("practice_id",staff.practiceId).order("service_date",{ascending:false}).limit(300),
  supabase.from("scheme_authorisation").select("id,patient_id,membership_id,encounter_id,request_reference,authorisation_number,status,request_date,decision_date,effective_from,effective_to,requested_amount,approved_amount,requested_units,approved_units,conditions,decline_reason,created_at").eq("practice_id",staff.practiceId).order("created_at",{ascending:false}).limit(100),
]);const patientMap=new Map((patients||[]).map((p:any)=>[p.id,p.display_name]));const membershipMap=new Map((memberships||[]).map((m:any)=>[m.id,m]));return <div className="space-y-6"><SectionHeader title="Medical Scheme Authorisations" body="Pre-authorisation requests and decisions are linked to the patient, verified scheme membership and encounter, then remain available to invoices and claims without re-keying."/><AuthorisationWorkspace practiceId={staff.practiceId} patients={(patients||[]) as any} memberships={(memberships||[]) as any} encounters={(encounters||[]) as any} authorisations={(authorisations||[]) as any}/><div className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Scheme / option</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Approved</th><th className="px-4 py-3">Validity</th></tr></thead><tbody>{(authorisations||[]).map((a:any)=>{const m:any=membershipMap.get(a.membership_id);return <tr key={a.id} className="border-t border-stone-100"><td className="px-4 py-3 font-medium">{patientMap.get(a.patient_id)||"Patient"}</td><td className="px-4 py-3 text-xs text-stone-600">{m?.scheme_name_snapshot||"—"}{m?.option_name_snapshot?` · ${m.option_name_snapshot}`:""}</td><td className="px-4 py-3"><p>{a.authorisation_number||a.request_reference||"—"}</p><p className="text-xs text-stone-500">requested {shortDate(a.request_date)}</p></td><td className="px-4 py-3"><StatusPill value={a.status}/></td><td className="px-4 py-3">{a.approved_amount==null?"—":money(a.approved_amount)}{a.approved_units!=null?<p className="text-xs text-stone-500">{a.approved_units} unit(s)</p>:null}</td><td className="px-4 py-3 text-xs text-stone-600">{shortDate(a.effective_from)}–{shortDate(a.effective_to)}</td></tr>})}</tbody></table></div>{!(authorisations||[]).length?<p className="p-6 text-sm text-stone-500">No scheme authorisations recorded.</p>:null}</div></div>}
