"use client";
import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
export function WorkItemActions({id,status,owned}:{id:string;status:string;owned:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);
 async function claim(){setBusy(true);setMessage(null);const{error}=await supabase.rpc("claim_operations_work_item",{p_work_item_id:id});setBusy(false);if(error)setMessage(error.message);else window.location.reload();}
 async function setStatus(next:string){const note=next==="blocked"?window.prompt("Blocked reason")||"":null;if(next==="blocked"&&(!note||note.trim().length<3))return;setBusy(true);setMessage(null);const{error}=await supabase.rpc("update_operations_work_item",{p_work_item_id:id,p_status:next,p_note:note});setBusy(false);if(error)setMessage(error.message);else window.location.reload();}
 return <div className="min-w-[150px]"><div className="flex flex-wrap gap-1">{!owned&&!["completed","cancelled"].includes(status)?<button type="button" disabled={busy} onClick={claim} className="rounded-lg bg-[#4a1f3e] px-2 py-1 text-xs text-white">Claim</button>:null}{status!=="in_progress"&&!['completed','cancelled'].includes(status)?<button type="button" disabled={busy} onClick={()=>setStatus("in_progress")} className="rounded-lg border px-2 py-1 text-xs">Start</button>:null}{!['waiting','completed','cancelled'].includes(status)?<button type="button" disabled={busy} onClick={()=>setStatus("waiting")} className="rounded-lg border px-2 py-1 text-xs">Wait</button>:null}{!['blocked','completed','cancelled'].includes(status)?<button type="button" disabled={busy} onClick={()=>setStatus("blocked")} className="rounded-lg border px-2 py-1 text-xs">Block</button>:null}{status!=="completed"&&status!=="cancelled"?<button type="button" disabled={busy} onClick={()=>setStatus("completed")} className="rounded-lg border px-2 py-1 text-xs">Complete</button>:null}</div>{message?<p className="mt-1 text-[11px] text-red-700">{message}</p>:null}</div>;
}
