"use client";
import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Capability={capability_key:string;display_name:string;capability_type:string;maximum_data_class:string;enabled_at_platform:boolean;practice_enabled:boolean;provider_config_id:string|null};
type Provider={id:string;display_name:string;capability_type:string;review_status:string;transport_ready:boolean;maximum_approved_data_class:string;phi_approved:boolean};
export function AssistPolicyControls({capabilities,providers,practiceId}:{capabilities:Capability[];providers:Provider[];practiceId:string}){
 const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState<string|null>(null);const[msg,setMsg]=useState<string|null>(null);
 async function setPolicy(c:Capability,enabled:boolean,providerId:string|null){setBusy(c.capability_key);setMsg(null);const{data,error}=await supabase.functions.invoke("practicectrl-assist-policy",{body:{capabilityKey:c.capability_key,providerConfigId:providerId,enabled,maxInputChars:4000,consentBasis:enabled?"Practice governance approval":null},headers:{"x-practicectrl-practice-id":practiceId}});setBusy(null);setMsg(error?.message||data?.error||(enabled?"Capability enabled under governed policy.":"Capability disabled."));if(!error&&!data?.error)window.location.reload();}
 return <div className="grid gap-3">{capabilities.map(c=>{const candidates=providers.filter(p=>p.capability_type===c.capability_type&&p.review_status==="approved"&&p.transport_ready);const provider=candidates[0];return <div key={c.capability_key} className="rounded-xl border border-stone-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium text-stone-800">{c.display_name}</p><p className="mt-1 text-xs text-stone-500">{c.capability_type} · max data class {c.maximum_data_class} · platform {c.enabled_at_platform?"enabled":"blocked"}</p></div><div className="flex gap-2">{c.practice_enabled?<button disabled={busy===c.capability_key} onClick={()=>setPolicy(c,false,null)} className="rounded-lg border border-stone-300 px-3 py-1.5 text-xs">Disable</button>:<button disabled={busy===c.capability_key||!c.enabled_at_platform||!provider} onClick={()=>setPolicy(c,true,provider?.id||null)} className="rounded-lg bg-[#4a1f3e] px-3 py-1.5 text-xs text-white disabled:opacity-40">Enable with approved provider</button>}</div></div>{!provider&&c.enabled_at_platform&&!c.practice_enabled?<p className="mt-2 text-xs text-amber-700">No approved transport-ready provider is available, so this capability remains blocked.</p>:null}</div>})}{msg?<p className="rounded-xl bg-stone-50 p-3 text-sm text-stone-700">{msg}</p>:null}</div>;
}
