"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Row = Record<string, any>;
type Props = {practiceId:string;role:string;profile:Row;billing:Row|null;operating:Row|null;locations:Row[];practitioners:Row[];appointmentTypes:Row[];relationships:Row[];policies:Row[];events:Row[];schemes:Row[]};
const field = "w-full border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900";
const label = "grid gap-1 text-sm font-medium text-slate-700";
const today = () => new Date().toISOString().slice(0,10);

export function PracticeConfigurationWorkspace({practiceId,role,profile,billing,operating,locations,practitioners,appointmentTypes,relationships,policies,events,schemes}:Props){
 const db=useMemo(()=>createClient(),[]);
 const [notice,setNotice]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const editable=role==="practice_manager"||role==="system_admin";
 const name=(id:string)=>schemes.find(s=>s.id===id)?.name||"Scheme unavailable";
 const checks=[
  {title:"Identity",ok:!!profile.legal_name,href:"#identity",reason:"Add the legal practice name"},
  {title:"Billing identity",ok:!!billing?.registration_number,href:"#identity",reason:"Add the provider registration number in the billing profile"},
  {title:"Locations",ok:locations.some(l=>l.active),href:"#locations",reason:"Add an active location"},
  {title:"Practitioners",ok:practitioners.some(p=>p.active),href:"#practitioners",reason:"Add an active practitioner"},
  {title:"Provider number",ok:practitioners.some(p=>p.active&&p.billing_provider_number),href:"#practitioners",reason:"Add a practitioner's billing provider number"},
  {title:"Diary defaults",ok:!!operating,href:"#diary",reason:"Save scheduling and intake defaults"},
  {title:"Appointment types",ok:appointmentTypes.some(a=>a.active),href:"#diary",reason:"Add an appointment type"},
  {title:"Payer relationship",ok:relationships.some(r=>r.status==="active"),href:"#payers",reason:"Approve and activate an accepted payer relationship"},
 ];
 async function submit(e:FormEvent<HTMLFormElement>,action:(values:FormData)=>Promise<{error:any}>,success:string){
  e.preventDefault();setError("");setNotice("");setBusy(true);
  try{const {error}=await action(new FormData(e.currentTarget));if(error)throw error;setNotice(success);window.setTimeout(()=>window.location.reload(),600)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}
 }
 function v(fd:FormData,key:string){return String(fd.get(key)||"").trim()}
 async function setActive(table:"practice_location"|"practitioner_profile"|"appointment_type",item:Row){
  setBusy(true);setError("");setNotice("");
  try{const {data,error}=await db.from(table).update({active:!item.active,updated_at:new Date().toISOString()}).eq("practice_id",practiceId).eq("id",item.id).select("id").single();if(error||!data)throw error||new Error("Update was not applied");setNotice(`${item.name||item.display_name} ${item.active?"deactivated":"activated"}.`);window.setTimeout(()=>window.location.reload(),600)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}
 }
 async function transition(table:"practice_payer_relationship"|"practice_policy",item:Row,next:"in_review"|"approved"|"active"|"retired"){
  setBusy(true);setError("");setNotice("");
  try{
   const user=(await db.auth.getUser()).data.user;
   const payload:Row={status:next,updated_at:new Date().toISOString()};
   if(next==="approved"){payload.approved_by=user?.id;payload.approved_at=new Date().toISOString()}
   const {data,error}=await db.from(table).update(payload).eq("practice_id",practiceId).eq("id",item.id).eq("status",item.status).select("id").single();
   if(error||!data)throw error||new Error("Configuration was not changed; refresh and try again");
   setNotice(`Configuration ${next.replaceAll("_"," ")}.`);window.setTimeout(()=>window.location.reload(),600);
  }catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}
 }
 function actionFor(item:Row,table:"practice_payer_relationship"|"practice_policy"){
  const next:Record<string,"in_review"|"approved"|"active"|"retired">={draft:"in_review",in_review:"approved",approved:"active",scheduled:"active",active:"retired"};
  const state=next[item.status];if(!editable||!state||(table==="practice_policy"&&state==="active"))return null;
  return <button type="button" disabled={busy} onClick={()=>transition(table,item,state)} className="ml-3 border border-teal-700 px-2 py-1 text-xs font-medium text-teal-800 disabled:opacity-50">{state==="in_review"?"Submit for review":state==="approved"?"Approve":state==="retired"?"Retire":"Activate"}</button>
 }
 return <div className="space-y-6">
  <nav aria-label="Practice Configuration sections" className="flex flex-wrap gap-3 border-b border-slate-200 pb-3 text-sm font-medium text-teal-800">{[["Readiness","readiness"],["Identity & branding","identity"],["Locations","locations"],["Practitioners","practitioners"],["Diary & intake","diary"],["Schemes & payers","payers"],["Policies","policies"],["Change history","history"],["Rule simulator","rule-simulator"]].map(([text,id])=><a key={id} className="underline-offset-4 hover:underline" href={`#${id}`}>{text}</a>)}</nav>
  {error?<p role="alert" className="border border-rose-300 bg-rose-50 p-3 text-sm text-rose-900">{error}</p>:null}
  {notice?<p role="status" className="border border-teal-300 bg-teal-50 p-3 text-sm text-teal-900">{notice}</p>:null}
  <section id="readiness" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Configuration readiness</h2><p className="mt-1 text-sm text-slate-600">{checks.filter(c=>c.ok).length} of {checks.length} explicit requirements complete. Each remaining item links to its configuration.</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map(c=><li key={c.title} className="border-l-2 border-slate-200 pl-3 text-sm"><span className="font-medium">{c.ok?"Complete":"Needs attention"}: {c.title}</span>{!c.ok?<span className="block text-slate-600"><a href={c.href} className="text-teal-800 underline">{c.reason}</a></span>:null}</li>)}</ul></section>
  <section id="identity" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Identity & branding</h2><p className="mt-1 text-sm text-slate-600">Legal and display identity use the existing practice record. Provider and VAT details remain in the existing billing profile.</p>
   <form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>submit(e,async fd=>db.rpc("update_practice_identity",{p_practice_id:practiceId,p_name:v(fd,"name"),p_legal_name:v(fd,"legal_name"),p_timezone:v(fd,"timezone"),p_brand_name:v(fd,"brand_name"),p_logo_url:v(fd,"logo_url")}),"Practice identity saved and audited.")}>
    <label className={label}>Practice name<input name="name" required maxLength={160} defaultValue={profile.name} disabled={!editable||busy} className={field}/></label>
    <label className={label}>Registered legal name<input name="legal_name" maxLength={160} defaultValue={profile.legal_name||""} disabled={!editable||busy} className={field}/></label>
    <label className={label}>Timezone<input name="timezone" required defaultValue={profile.timezone||"Africa/Johannesburg"} disabled={!editable||busy} className={field}/></label>
    <label className={label}>Patient-facing display name<input name="brand_name" maxLength={160} defaultValue={profile.branding?.display_name||""} disabled={!editable||busy} className={field}/></label>
    <label className={label}>Approved HTTPS logo URL<input name="logo_url" type="url" maxLength={500} defaultValue={profile.branding?.logo_url||""} disabled={!editable||busy} className={field}/></label>
    {editable?<button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Save identity</button>:null}
   </form><h3 className="mt-6 font-semibold text-[#10223c]">Provider & contact details</h3><p className="mt-1 text-sm text-slate-600">The billing profile is shared with invoicing. Banking information remains restricted to the billing domain.</p>
   <form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={e=>submit(e,async fd=>db.from("practice_billing_profile").upsert({practice_id:practiceId,legal_name:v(fd,"legal_name")||profile.legal_name,trading_name:v(fd,"trading_name")||null,registration_number:v(fd,"registration_number")||null,vat_registered:fd.has("vat_registered"),vat_registration_number:v(fd,"vat_registration_number")||null,email:v(fd,"email")||null,phone:v(fd,"phone")||null,invoice_footer:v(fd,"invoice_footer")||null,statement_footer:v(fd,"statement_footer")||null,updated_by:(await db.auth.getUser()).data.user?.id}),"Provider and contact details saved.")}>
    <label className={label}>Trading name<input name="trading_name" defaultValue={billing?.trading_name||profile.name} disabled={!editable||busy} className={field}/></label><label className={label}>Practice / provider number<input name="registration_number" defaultValue={billing?.registration_number||""} disabled={!editable||busy} className={field}/></label><label className={label}>Contact email<input name="email" type="email" defaultValue={billing?.email||""} disabled={!editable||busy} className={field}/></label><label className={label}>Contact phone<input name="phone" type="tel" defaultValue={billing?.phone||""} disabled={!editable||busy} className={field}/></label><label className={label}>VAT number<input name="vat_registration_number" defaultValue={billing?.vat_registration_number||""} disabled={!editable||busy} className={field}/></label><label className={label}><span><input type="checkbox" name="vat_registered" defaultChecked={billing?.vat_registered||false} disabled={!editable||busy}/> VAT registered</span></label><label className={label}>Invoice footer<input name="invoice_footer" defaultValue={billing?.invoice_footer||""} disabled={!editable||busy} className={field}/></label><label className={label}>Statement footer<input name="statement_footer" defaultValue={billing?.statement_footer||""} disabled={!editable||busy} className={field}/></label><input type="hidden" name="legal_name" value={profile.legal_name||""}/>{editable?<button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Save provider details</button>:null}
   </form>
  </section>
  <section id="locations" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Locations</h2><ul className="mt-3 divide-y divide-slate-200 text-sm">{locations.map(l=><li key={l.id} className="py-2">{l.name} · {l.location_type||"Location"} · {l.timezone||profile.timezone} · {l.active?"Active":"Inactive"}{editable?<button type="button" disabled={busy} onClick={()=>setActive("practice_location",l)} className="ml-3 text-teal-800 underline">{l.active?"Deactivate":"Activate"}</button>:null}</li>)}{!locations.length?<li className="py-2">No locations configured.</li>:null}</ul>
   {editable?<form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={e=>submit(e,async fd=>db.from("practice_location").insert({practice_id:practiceId,name:v(fd,"name"),location_type:v(fd,"type")||"practice",timezone:v(fd,"timezone")||profile.timezone,created_by:(await db.auth.getUser()).data.user?.id}),"Location added.")}><label className={label}>Location name<input name="name" required className={field}/></label><label className={label}>Location type<select name="type" className={field}><option value="practice">Practice</option><option value="consulting_room">Consulting room</option><option value="procedure_room">Procedure room</option><option value="telehealth">Telehealth</option><option value="other">Other</option></select></label><label className={label}>Timezone<input name="timezone" defaultValue={profile.timezone||"Africa/Johannesburg"} className={field}/></label><button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-3">Add location</button></form>:null}
  </section>
  <section id="practitioners" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Practitioners</h2><ul className="mt-3 divide-y divide-slate-200 text-sm">{practitioners.map(p=><li key={p.id} className="py-2">{p.display_name} · {p.speciality||p.profession||"Specialty pending"} · HPCSA {p.hpcsa_number||"missing"} · Billing provider {p.billing_provider_number||"missing"} · {p.active?"Active":"Inactive"}{editable?<button type="button" disabled={busy} onClick={()=>setActive("practitioner_profile",p)} className="ml-3 text-teal-800 underline">{p.active?"Deactivate":"Activate"}</button>:null}</li>)}{!practitioners.length?<li className="py-2">No practitioner profiles.</li>:null}</ul>
   {editable?<form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={e=>submit(e,async fd=>db.from("practitioner_profile").insert({practice_id:practiceId,display_name:v(fd,"display_name"),profession:v(fd,"profession"),speciality:v(fd,"speciality")||null,hpcsa_number:v(fd,"hpcsa_number")||null,billing_provider_number:v(fd,"billing_provider_number")||null,default_location_id:v(fd,"location_id")||null,created_by:(await db.auth.getUser()).data.user?.id}),"Practitioner profile added.")}><label className={label}>Name<input name="display_name" required className={field}/></label><label className={label}>Profession<input name="profession" required className={field}/></label><label className={label}>Specialty<input name="speciality" className={field}/></label><label className={label}>HPCSA number<input name="hpcsa_number" className={field}/></label><label className={label}>Billing provider number<input name="billing_provider_number" className={field}/></label><label className={label}>Primary location<select name="location_id" className={field}><option value="">No primary location</option>{locations.filter(l=>l.active).map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label><button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-3">Add practitioner</button></form>:null}
  </section>
  <section id="diary" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Diary & patient administration</h2><p className="mt-1 text-sm text-slate-600">The PMS owns appointments. These defaults govern PracticeCtrl intake and handoff; they do not create a second diary.</p>
   <form className="mt-4 grid gap-3 sm:grid-cols-3" onSubmit={e=>submit(e,async fd=>db.from("practice_operating_config").upsert({practice_id:practiceId,appointment_source:"PMS",default_appointment_minutes:Number(v(fd,"duration")),cancellation_notice_hours:Number(v(fd,"cancellation")),require_patient_contact:fd.has("contact"),require_scheme_membership:fd.has("membership"),require_identity_review:fd.has("identity"),default_currency:"ZAR",updated_by:(await db.auth.getUser()).data.user?.id}),"Diary and intake defaults saved.")}><label className={label}>Default duration (minutes)<input name="duration" type="number" min={5} max={480} defaultValue={operating?.default_appointment_minutes||30} disabled={!editable||busy} className={field}/></label><label className={label}>Cancellation notice (hours)<input name="cancellation" type="number" min={0} max={720} defaultValue={operating?.cancellation_notice_hours??24} disabled={!editable||busy} className={field}/></label><div className="text-sm">Appointment source: <strong>PMS</strong></div><label className={label}><span><input name="contact" type="checkbox" defaultChecked={operating?.require_patient_contact??true} disabled={!editable||busy}/> Patient contact required</span></label><label className={label}><span><input name="membership" type="checkbox" defaultChecked={operating?.require_scheme_membership??false} disabled={!editable||busy}/> Scheme membership required</span></label><label className={label}><span><input name="identity" type="checkbox" defaultChecked={operating?.require_identity_review??true} disabled={!editable||busy}/> Identity review required</span></label>{editable?<button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-3">Save operating defaults</button>:null}</form>
   <h3 className="mt-6 font-semibold">Appointment types</h3><ul className="mt-2 text-sm">{appointmentTypes.map(a=><li key={a.id}>{a.name} · {a.duration_minutes} min · {a.requires_authorisation?"Authorisation assessment":"Standard"}</li>)}{!appointmentTypes.length?<li>No appointment types configured.</li>:null}</ul>
   {editable?<form className="mt-3 flex flex-wrap gap-3" onSubmit={e=>submit(e,async fd=>db.from("appointment_type").insert({practice_id:practiceId,name:v(fd,"name"),duration_minutes:Number(v(fd,"minutes")),requires_authorisation:fd.has("auth"),created_by:(await db.auth.getUser()).data.user?.id}),"Appointment type added for PMS handoff.")}><label className={label}>Type name<input name="name" required className={field}/></label><label className={label}>Minutes<input name="minutes" type="number" min={5} max={480} defaultValue={30} required className={field}/></label><label className="self-end text-sm"><input type="checkbox" name="auth"/> Assess authorisation</label><button disabled={busy} className="self-end bg-teal-800 px-4 py-2 text-sm font-semibold text-white">Add type</button></form>:null}
  </section>
  <section id="payers" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Schemes & payers</h2><p className="mt-1 text-sm text-slate-600">Reference schemes are shared. A relationship records whether this practice accepts a scheme, independently of an agreement. Billing still uses approved payer contracts and rules; relationship-based claim gating awaits Rules V2.</p><ul className="mt-3 divide-y divide-slate-200 text-sm">{relationships.map(r=><li key={r.id} className="py-2">{name(r.medical_scheme_id)} · {r.relationship_type.replaceAll("_"," ")} · {r.accepted?"Accepted":"Not accepted"} · v{r.version} · {r.status} · from {r.effective_from}{actionFor(r,"practice_payer_relationship")}</li>)}{!relationships.length?<li className="py-2">No payer relationships recorded.</li>:null}</ul>
   {editable?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>submit(e,async fd=>db.from("practice_payer_relationship").insert({practice_id:practiceId,medical_scheme_id:v(fd,"scheme"),relationship_type:v(fd,"relationship"),accepted:fd.has("accepted"),effective_from:v(fd,"effective_from"),version:1+Math.max(0,...relationships.filter(r=>r.medical_scheme_id===v(fd,"scheme")).map(r=>r.version)),created_by:(await db.auth.getUser()).data.user?.id}),"Payer relationship draft saved for review.")}><label className={label}>Medical scheme<select name="scheme" required className={field}><option value="">Select scheme</option>{schemes.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className={label}>Relationship<select name="relationship" className={field}><option value="unknown">Not yet verified</option><option value="contracted">Contracted</option><option value="non_contracted">Non-contracted</option></select></label><label className={label}>Effective from<input type="date" name="effective_from" required defaultValue={today()} className={field}/></label><label className={label}><span><input type="checkbox" name="accepted" defaultChecked/> Accept this scheme</span></label><button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Save relationship draft</button></form>:null}
   <Link className="mt-4 inline-block text-sm font-medium text-teal-800 underline" href="/contracts">Manage agreements and simulate payer rules</Link>
  </section>
  <section id="policies" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Policies & procedures</h2><p className="mt-1 text-sm text-slate-600">Draft SOPs and structured triggers are stored with version and effective date. Policies can be reviewed and approved but cannot become active until enforcement creates governed Operations work; approval alone does not block care.</p><ul className="mt-3 divide-y divide-slate-200 text-sm">{policies.map(p=><li key={p.id} className="py-2">{p.title} · {p.category} · v{p.version} · {p.status} · from {p.effective_from}{p.blocking?" · intended blocker":""}{actionFor(p,"practice_policy")}</li>)}{!policies.length?<li className="py-2">No policies drafted.</li>:null}</ul>
   {editable?<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={e=>submit(e,async fd=>db.from("practice_policy").insert({practice_id:practiceId,policy_key:v(fd,"key"),title:v(fd,"title"),category:v(fd,"category"),sop:v(fd,"sop"),effective_from:v(fd,"effective_from"),trigger_kind:v(fd,"trigger")||null,owner_role:v(fd,"owner")||null,due_hours:v(fd,"due_hours")?Number(v(fd,"due_hours")):null,blocking:fd.has("blocking"),version:1+Math.max(0,...policies.filter(p=>p.policy_key===v(fd,"key")).map(p=>p.version)),created_by:(await db.auth.getUser()).data.user?.id}),"Policy draft recorded. It does not yet execute.")}><label className={label}>Policy key<input name="key" required pattern="[a-z0-9_]{3,80}" placeholder="elective_authorisation" className={field}/></label><label className={label}>Title<input name="title" required className={field}/></label><label className={label}>Category<input name="category" required placeholder="Authorisations" className={field}/></label><label className={label}>Effective from<input type="date" name="effective_from" required defaultValue={today()} className={field}/></label><label className={label}>Workflow trigger<input name="trigger" placeholder="appointment_confirmed_in_pms" className={field}/></label><label className={label}>Responsible role<select name="owner" className={field}><option value="">Unassigned</option>{["reception","billing","finance","practice_manager","clinical_admin","system_admin","practitioner","coder"].map(r=><option key={r} value={r}>{r.replaceAll("_"," ")}</option>)}</select></label><label className={label}>Due within hours<input name="due_hours" type="number" min={0} className={field}/></label><label className={label}><span><input name="blocking" type="checkbox"/> Blocks workflow when enforced</span></label><label className={`${label} sm:col-span-2`}>Human-readable procedure<textarea name="sop" required rows={3} className={field}/></label><button disabled={busy} className="bg-teal-800 px-4 py-2 text-sm font-semibold text-white sm:col-span-2">Save policy draft</button></form>:null}
  </section>
  <section id="history" className="border border-slate-200 bg-white p-5"><h2 className="text-xl font-semibold text-[#10223c]">Configuration change history</h2><ul className="mt-3 divide-y divide-slate-200 text-sm">{events.map(ev=><li key={ev.id} className="py-2">{new Date(ev.created_at).toLocaleString("en-ZA")} · {ev.entity_type.replaceAll("_"," ")} · {ev.action} · actor {ev.actor_user_id?.slice(0,8)||"system"}<details className="mt-1 text-xs text-slate-600"><summary className="cursor-pointer text-teal-800">Inspect change</summary><pre className="mt-2 overflow-x-auto whitespace-pre-wrap">{JSON.stringify({before:ev.before_value,after:ev.after_value},null,2)}</pre></details></li>)}{!events.length?<li className="py-2">No recorded changes.</li>:null}</ul></section>
 </div>;
}
