"use client";
import {useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {StaffRole} from "@/lib/auth/roles";

type Step={id:string;run_id:string;step_key:string;sequence:number;label:string;status:"pending"|"passed"|"failed"|"blocked"|"skipped";notes:string|null;evidence:Record<string,unknown>;updated_at:string};
type Run={id:string;release_version:string;environment:string;status:string;started_at:string;completed_at:string|null;created_at:string};
type ProbeCheck={key:string;label:string;passed:boolean;detail:string};
type Probe={id:string;release_version:string;probe_version:string;checks:ProbeCheck[];passed_count:number;failed_count:number;all_passed:boolean;created_at:string};
type Blocker={code:string;scope:string;message:string};
type Dependency={code:string;category:string;scope:string;status:string;blocking:boolean;detail:string;description?:string;priority?:string;owner?:string|null;external_reference?:string|null};
type Dependencies={blocking_staging_count?:number;blocking_production_count?:number;waiting_external_count?:number;items?:Dependency[]};
type Artifact={id:string;release_version:string;environment:string;deployment_provider:string;project_ref:string|null;deployment_ref:string|null;deployment_url:string;exact_origin:string;build_status:string;test_status:string;health_status:string;verified_at:string|null;created_at:string};
type Scenario={id:string;validation_run_id:string|null;release_version:string;scenario_key:string;status:string;started_at:string;completed_at:string|null;created_at:string};
type Checkpoint={id:string;run_id:string;sequence:number;checkpoint_key:string;label:string;status:Step["status"];notes:string|null;evidence:Record<string,unknown>;updated_at:string};
type Readiness={release_target?:string;staging_ready?:boolean;production_ready?:boolean;automated_checks?:{checks?:ProbeCheck[];passed_count?:number;failed_count?:number;all_passed?:boolean};latest_validation_run?:any;latest_e2e_scenario?:any;dependencies?:any;blockers?:Blocker[]};

const tone=(ok:boolean)=>ok?"border-emerald-200 bg-emerald-50 text-emerald-900":"border-amber-200 bg-amber-50 text-amber-900";
const statusTone=(s:string)=>s==="passed"||s==="satisfied"?"border-emerald-200 bg-emerald-50 text-emerald-800":s==="failed"?"border-rose-200 bg-rose-50 text-rose-800":s==="blocked"||s==="waiting_external"?"border-amber-200 bg-amber-50 text-amber-800":"border-stone-200 bg-stone-50 text-stone-700";

export function ReleaseReadinessWorkspace({practiceId,role,releaseTarget,readiness,dependencies,runs,steps,latestProbe,artifacts,scenarios,checkpoints}:{practiceId:string;role:StaffRole;releaseTarget:string;readiness:Readiness;dependencies:Dependencies;runs:Run[];steps:Step[];latestProbe:Probe|null;artifacts:Artifact[];scenarios:Scenario[];checkpoints:Checkpoint[]}){
 const supabase=useMemo(()=>createClient(),[]);
 const[busy,setBusy]=useState<string|null>(null);
 const[msg,setMsg]=useState<string|null>(null);
 const canManage=["practice_manager","system_admin"].includes(role);
 const canProbe=canManage||role==="auditor";
 const latestRun=runs[0]||null;
 const latestScenario=scenarios[0]||null;
 const liveChecks=readiness.automated_checks?.checks||[];

 async function startRun(){if(!canManage)return;if(!window.confirm(`Start a new 12-step ${releaseTarget} staging validation run using synthetic/test patient data only?`))return;setBusy("new");setMsg(null);const{error}=await supabase.rpc("create_release_validation_run",{p_practice_id:practiceId,p_release_version:releaseTarget});setBusy(null);if(error)setMsg(error.message);else window.location.reload();}
 async function startScenario(){if(!canManage)return;if(!window.confirm("Start a closed-loop synthetic revenue-cycle scenario? No real patient data may be used."))return;setBusy("scenario");setMsg(null);const{error}=await supabase.rpc("create_release_e2e_scenario_run",{p_practice_id:practiceId,p_release_version:releaseTarget,p_validation_run_id:latestRun?.id||null});setBusy(null);if(error)setMsg(error.message);else window.location.reload();}
 async function runProbe(){if(!canProbe)return;setBusy("probe");setMsg(null);const{data,error}=await supabase.functions.invoke("practicectrl-release-probe",{headers:{"x-practicectrl-practice-id":practiceId},body:{runId:latestRun?.id||null}});setBusy(null);if(error||data?.error)setMsg(data?.error||error?.message||"Automated staging probe failed.");else window.location.reload();}
 async function setStep(step:Step,status:Step["status"]){if(!canManage)return;let notes=step.notes||"";if(status==="failed"||status==="blocked"){const entered=window.prompt("Record the blocker/failure reason. Do not include patient-identifying information.",notes);if(entered===null)return;notes=entered.trim();if(!notes){setMsg("A failure or blocker reason is required.");return;}}else if(status==="passed"&&!notes){notes="Passed during controlled staging validation.";}setBusy(step.id);setMsg(null);const{error}=await supabase.rpc("update_release_validation_step",{p_step_id:step.id,p_status:status,p_notes:notes||null,p_evidence:{recorded_from:"release_readiness_ui",contains_phi:false,release_version:releaseTarget}});setBusy(null);if(error)setMsg(error.message);else window.location.reload();}
 async function setCheckpoint(cp:Checkpoint,status:Checkpoint["status"]){if(!canManage)return;let notes=cp.notes||"";if(status==="failed"||status==="blocked"){const entered=window.prompt("Record the checkpoint blocker/failure. Use synthetic identifiers only.",notes);if(entered===null)return;notes=entered.trim();if(!notes){setMsg("A failure or blocker reason is required.");return;}}else if(status==="passed"&&!notes){notes="Checkpoint passed with synthetic/test data.";}setBusy(cp.id);setMsg(null);const{error}=await supabase.rpc("update_release_e2e_scenario_checkpoint",{p_checkpoint_id:cp.id,p_status:status,p_notes:notes||null,p_evidence:{recorded_from:"release_readiness_ui",contains_phi:false,synthetic_only:true}});setBusy(null);if(error)setMsg(error.message);else window.location.reload();}

 return <div className="space-y-6">
  <section className="grid gap-4 xl:grid-cols-2"><GateSummary title="Staging gate" ready={Boolean(readiness.staging_ready)} body={readiness.staging_ready?"Verified 0.34 artifact, MFA, technical probe and staging prerequisites are ready for controlled UAT.":"Staging remains fail-closed until all current 0.34 machine checks and stored probe evidence pass."}/><GateSummary title="Production gate" ready={Boolean(readiness.production_ready)} body={readiness.production_ready?"All recorded production gates are satisfied.":"Production remains fail-closed until controlled UAT, the closed-loop scenario, source licensing and external production rails are complete."}/></section>

  <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">Current release target</p><h3 className="mt-1 text-xl font-semibold text-[#173B5E]">{releaseTarget}</h3><p className="mt-1 text-sm text-stone-600">Calculated checks show current state; the stored probe is immutable release evidence.</p></div>{canProbe?<button disabled={busy!==null} onClick={runProbe} className="rounded-xl border border-[#173B5E] px-4 py-2 text-sm font-semibold text-[#173B5E] disabled:opacity-50">{busy==="probe"?"Checking…":"Run v0.34 probe"}</button>:null}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{liveChecks.map(c=><div key={c.key} className={`rounded-xl border p-3 ${tone(c.passed)}`}><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{c.label}</p><span className="text-[11px] font-bold">{c.passed?"PASS":"GATED"}</span></div><p className="mt-1 text-xs opacity-80">{c.detail}</p></div>)}</div>{latestProbe?<p className="mt-4 text-xs text-stone-500">Stored evidence: {latestProbe.probe_version} · {latestProbe.passed_count} passed / {latestProbe.failed_count} gated · {new Date(latestProbe.created_at).toLocaleString("en-ZA")}</p>:<p className="mt-4 text-xs text-amber-700">No stored v0.34 probe evidence yet.</p>}</section>

  <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">Deployment evidence</p><h3 className="mt-1 text-lg font-semibold text-[#173B5E]">Dedicated PracticeCtrl staging artifact</h3><p className="mt-1 text-sm text-stone-600">The Dr Tini public marketing site does not qualify. Evidence must match the exact registered PracticeCtrl staging origin.</p></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${artifacts.some(a=>a.environment==="staging"&&a.build_status==="passed"&&a.test_status==="passed"&&a.health_status==="passed")?statusTone("passed"):statusTone("blocked")}`}>{artifacts.length?`${artifacts.length} record(s)`:"NO ARTIFACT"}</span></div><div className="mt-4 grid gap-2">{artifacts.map(a=><div key={a.id} className="rounded-xl border border-stone-200 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium text-[#173B5E]">{a.deployment_url}</span><span className={`rounded-full border px-2.5 py-1 text-xs ${statusTone(a.build_status==="passed"&&a.test_status==="passed"&&a.health_status==="passed"?"passed":"blocked")}`}>{a.environment}</span></div><p className="mt-1 text-xs text-stone-500">Build {a.build_status} · tests {a.test_status} · health {a.health_status} · origin {a.exact_origin}</p></div>)}{!artifacts.length?<p className="text-sm text-stone-500">No verified staging artifact exists yet. The Vercel deployment rail is the current external blocker.</p>:null}</div></section>

  <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">External dependency register</p><h3 className="mt-1 text-lg font-semibold text-[#173B5E]">Authoritative blockers, not a duplicate spreadsheet</h3><p className="mt-1 text-sm text-stone-600">Generated from deployment evidence, MFA/source state and the existing integration-requirement records.</p></div><div className="flex gap-2 text-xs"><span className="rounded-full bg-amber-50 px-3 py-1 font-semibold text-amber-800">{dependencies.blocking_staging_count??0} staging</span><span className="rounded-full bg-rose-50 px-3 py-1 font-semibold text-rose-800">{dependencies.blocking_production_count??0} production</span><span className="rounded-full bg-stone-100 px-3 py-1 font-semibold text-stone-700">{dependencies.waiting_external_count??0} waiting external</span></div></div><div className="mt-4 grid gap-2">{(dependencies.items||[]).slice(0,40).map(d=><div key={d.code} className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[11px] text-stone-500">{d.code}</span><span className={`rounded-full border px-2 py-0.5 text-[11px] font-semibold ${statusTone(d.status)}`}>{d.status}</span><span className="rounded-full bg-stone-100 px-2 py-0.5 text-[11px] text-stone-600">{d.scope}</span>{d.priority?<span className="text-[11px] uppercase text-stone-400">{d.priority}</span>:null}</div><p className="mt-1 text-sm text-stone-700">{d.detail}</p>{d.description&&d.description!==d.detail?<p className="mt-1 text-xs text-stone-500">{d.description}</p>:null}</div>)}</div></section>

  <section className="rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-stone-200 p-5"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">Controlled UAT</p><h3 className="mt-1 text-lg font-semibold text-[#173B5E]">12-step release validation</h3><p className="mt-1 text-sm text-stone-600">The original 12-stage flow now covers Pathology, Medicines, Practice Economics, Recovery and governed communications within the same release chain.</p></div>{canManage?<button disabled={busy!==null} onClick={startRun} className="rounded-xl bg-[#173B5E] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy==="new"?"Starting…":"Start 0.34 UAT run"}</button>:<span className="rounded-full bg-stone-100 px-3 py-1 text-xs text-stone-600">Auditor: read only</span>}</div>{latestRun?<div className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{latestRun.release_version} · {latestRun.environment}</p><p className="text-xs text-stone-500">Started {new Date(latestRun.started_at).toLocaleString("en-ZA")}</p></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusTone(latestRun.status)}`}>{latestRun.status}</span></div><div className="grid gap-2">{steps.map(step=><ValidationRow key={step.id} item={step} canManage={canManage} busy={busy} onSet={setStep}/>)}</div></div>:<p className="p-5 text-sm text-stone-500">No {releaseTarget} validation run has been started.</p>}</section>

  <section className="rounded-2xl border border-stone-200 bg-white shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-stone-200 p-5"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">Closed-loop scenario</p><h3 className="mt-1 text-lg font-semibold text-[#173B5E]">Synthetic patient: clinical work → payment → recovery</h3><p className="mt-1 text-sm text-stone-600">Proves the modules work as one product. Real patient data is prohibited in this scenario.</p></div>{canManage?<button disabled={busy!==null} onClick={startScenario} className="rounded-xl border border-[#173B5E] px-4 py-2 text-sm font-semibold text-[#173B5E] disabled:opacity-50">{busy==="scenario"?"Starting…":"Start closed-loop scenario"}</button>:null}</div>{latestScenario?<div className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">{latestScenario.scenario_key}</p><p className="text-xs text-stone-500">Started {new Date(latestScenario.started_at).toLocaleString("en-ZA")}</p></div><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${statusTone(latestScenario.status)}`}>{latestScenario.status}</span></div><div className="grid gap-2">{checkpoints.map(cp=><ValidationRow key={cp.id} item={cp} canManage={canManage} busy={busy} onSet={setCheckpoint}/>)}</div></div>:<p className="p-5 text-sm text-stone-500">No closed-loop {releaseTarget} scenario has been started.</p>}</section>

  <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#25A6A1]">Fail-closed blockers</p><h3 className="mt-1 text-lg font-semibold text-[#173B5E]">Calculated release blockers</h3></div><span className="rounded-full bg-stone-100 px-3 py-1 text-xs font-semibold text-stone-700">{readiness.blockers?.length??0}</span></div><div className="mt-4 grid gap-2">{(readiness.blockers||[]).map(b=><div key={`${b.scope}:${b.code}`} className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-stone-500">{b.code}</span><span className="rounded-full bg-stone-100 px-2 py-0.5 text-[11px] text-stone-600">{b.scope}</span></div><p className="mt-1 text-sm text-stone-700">{b.message}</p></div>)}</div></section>
  {msg?<p className="rounded-xl bg-stone-100 p-3 text-sm text-stone-700">{msg}</p>:null}
 </div>;
}

function ValidationRow({item,canManage,busy,onSet}:{key?:string;item:Step|Checkpoint;canManage:boolean;busy:string|null;onSet:(item:any,status:Step["status"])=>void}){return <div className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium"><span className="mr-2 text-xs text-stone-400">{item.sequence}.</span>{item.label}</p>{item.notes?<p className="mt-1 text-xs text-stone-500">{item.notes}</p>:null}</div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2.5 py-1 text-xs font-medium ${statusTone(item.status)}`}>{item.status}</span>{canManage?<><button disabled={busy!==null} onClick={()=>onSet(item,"passed")} className="rounded-lg border border-emerald-200 px-2.5 py-1 text-xs font-medium text-emerald-800 disabled:opacity-40">Pass</button><button disabled={busy!==null} onClick={()=>onSet(item,"blocked")} className="rounded-lg border border-amber-200 px-2.5 py-1 text-xs font-medium text-amber-800 disabled:opacity-40">Block</button><button disabled={busy!==null} onClick={()=>onSet(item,"failed")} className="rounded-lg border border-rose-200 px-2.5 py-1 text-xs font-medium text-rose-800 disabled:opacity-40">Fail</button></>:null}</div></div></div>}
function GateSummary({title,ready,body}:{title:string;ready:boolean;body:string}){return <article className={`rounded-2xl border p-5 ${tone(ready)}`}><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-semibold">{title}</h3><span className="rounded-full border border-current/20 px-3 py-1 text-xs font-bold">{ready?"READY":"NOT READY"}</span></div><p className="mt-2 text-sm opacity-80">{body}</p></article>}
