"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { StaffRole } from "@/lib/auth/roles";

type Member={user_id:string;email:string|null;role:string;active:boolean;created_at:string};
type Invite={id:string;email:string;role:string;status:string;expires_at:string;sent_at:string|null;created_at:string};
export function StaffAccessPanel({role,practiceId}:{role:StaffRole;practiceId:string}){
  const supabase=useMemo(()=>createClient(),[]); const [members,setMembers]=useState<Member[]>([]); const[invites,setInvites]=useState<Invite[]>([]);
  const[busy,setBusy]=useState(false); const[msg,setMsg]=useState<string|null>(null); const[error,setError]=useState<string|null>(null);
  async function load(){const {data,error:e}=await supabase.functions.invoke("practicectrl-staff-directory",{body:{},headers:{"x-practicectrl-practice-id":practiceId}});if(e||data?.error){setError(data?.error||e?.message||"Could not load staff directory.");return;}setMembers(data.members||[]);setInvites(data.invites||[]);}
  useEffect(()=>{void load();},[]);
  async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg(null);setError(null);const fd=new FormData(e.currentTarget);const{data,error:err}=await supabase.functions.invoke("practicectrl-staff-invite",{body:{email:String(fd.get("email")||""),role:String(fd.get("role")||"")},headers:{"x-practicectrl-practice-id":practiceId}});setBusy(false);if(err||data?.error){setError(data?.error||err?.message||"Invitation failed.");return;}setMsg(data.message||"Invitation sent.");e.currentTarget.reset();await load();}
  const roles=role==="system_admin"?["practitioner","reception","billing","finance","coder","practice_manager","clinical_admin","auditor","system_admin"]:["practitioner","reception","billing","coder","clinical_admin"];
  return <div className="space-y-4">
    {role!=="auditor"?<form onSubmit={invite} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Invite staff member</h3><p className="mt-1 text-sm text-stone-500">Invitations expire after 48 hours. Privileged roles are restricted to system administrators.</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_220px_auto]"><input name="email" type="email" required placeholder="staff@example.com" className="rounded-xl border border-stone-300 px-3 py-2 text-sm"/><select name="role" className="rounded-xl border border-stone-300 px-3 py-2 text-sm">{roles.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><button disabled={busy} className="rounded-xl bg-[#4a1f3e] px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{busy?"Sending…":"Send invite"}</button></div></form>:null}
    {error?<p className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>:null}{msg?<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{msg}</p>:null}
    <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Active staff</h3><div className="mt-4 grid gap-2">{members.map(m=><div key={m.user_id} className="rounded-xl border border-stone-200 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{m.email||m.user_id.slice(0,8)}</p><span className="rounded-full bg-stone-100 px-2 py-1 text-xs">{m.active?"active":"inactive"}</span></div><p className="mt-1 text-xs text-stone-500">{m.role.replaceAll("_"," ")} · added {new Date(m.created_at).toLocaleString("en-ZA")}</p></div>)}{!members.length?<p className="text-sm text-stone-500">No accepted staff members yet.</p>:null}</div></section>
    <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Recent invitations</h3><div className="mt-4 grid gap-2">{invites.map(i=><div key={i.id} className="rounded-xl border border-stone-200 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-medium">{i.email}</p><span className="rounded-full bg-stone-100 px-2 py-1 text-xs">{i.status}</span></div><p className="mt-1 text-xs text-stone-500">{i.role.replaceAll("_"," ")} · expires {new Date(i.expires_at).toLocaleString("en-ZA")}</p></div>)}{!invites.length?<p className="text-sm text-stone-500">No invitations recorded yet.</p>:null}</div></section></div>
  </div>;
}
