"use client";
import { FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Invoice={id:string;invoice_number:string;status:string;medical_scheme_id:string|null;medical_scheme_option_id:string|null};
type Line={id:string;invoice_id:string;line_no:number;code_system:string|null;code:string|null;description_snapshot:string;line_amount:number;claim_eligible:boolean;reference_amount:number|null;expected_contractual_amount:number|null;expected_scheme_amount:number|null;expected_patient_liability:number|null;payer_rule_resolution_id:string|null};
type Practitioner={id:string;display_name:string};
export function PayerResolutionPanel({invoices,lines,practitioners}:{invoices:Invoice[];lines:Line[];practitioners:Practitioner[]}){
 const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState<string|null>(null);const[msg,setMsg]=useState<string|null>(null);const eligible=lines.filter(l=>l.claim_eligible&&invoices.some(i=>i.id===l.invoice_id&&i.medical_scheme_id));
 async function resolve(e:FormEvent<HTMLFormElement>,line:Line){e.preventDefault();setBusy(line.id);setMsg(null);const fd=new FormData(e.currentTarget);const practitioner=String(fd.get("practitionerId")||"")||null;const reference=Number(fd.get("referenceAmount"));const{error}=await supabase.rpc("record_invoice_line_payer_resolution",{p_invoice_line_id:line.id,p_practitioner_id:practitioner,p_reference_amount:reference});setBusy(null);if(error)setMsg(error.message);else{setMsg("Contract rule resolved and expected reimbursement recorded. Revenue Integrity can now reassess the invoice.");window.location.reload();}}
 return <section className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-semibold text-[#4a1f3e]">Manual payer-resolution fallback</h3><p className="mt-1 text-sm text-stone-500">Automated claim pre-flight resolves contract-backed lines first. Use this control only to review or re-resolve a line manually when a reference tariff or practitioner context needs correction.</p>{msg?<p className="mt-3 rounded-xl bg-stone-50 p-3 text-sm text-stone-700">{msg}</p>:null}<div className="mt-4 grid gap-3">{eligible.map(l=>{const inv=invoices.find(i=>i.id===l.invoice_id)!;return <div key={l.id} className="rounded-xl border border-stone-200 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-medium">{inv.invoice_number} · line {l.line_no} · {l.code||"No code"}</p><p className="mt-1 text-xs text-stone-500">{l.description_snapshot} · charged R{Number(l.line_amount).toFixed(2)}</p>{l.payer_rule_resolution_id?<p className="mt-1 text-xs text-emerald-700">Resolved · expected scheme R{Number(l.expected_scheme_amount||0).toFixed(2)} · estimated patient R{Number(l.expected_patient_liability||0).toFixed(2)}</p>:<p className="mt-1 text-xs text-amber-700">Not yet resolved against an effective contract rule.</p>}</div><form onSubmit={(e:FormEvent<HTMLFormElement>)=>resolve(e,l)} className="grid min-w-[280px] gap-2 sm:grid-cols-[1fr_120px_auto]"><select name="practitionerId" className="rounded-lg border border-stone-300 px-2 py-1.5 text-xs"><option value="">Practice-wide</option>{practitioners.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select><input name="referenceAmount" required type="number" min="0" step="0.01" defaultValue={l.reference_amount??""} placeholder="Reference R" className="rounded-lg border border-stone-300 px-2 py-1.5 text-xs"/><button disabled={busy===l.id} className="rounded-lg bg-[#4a1f3e] px-2.5 py-1.5 text-xs font-medium text-white disabled:opacity-50">{busy===l.id?"Resolving…":l.payer_rule_resolution_id?"Re-resolve":"Resolve"}</button></form></div></div>})}{!eligible.length?<p className="text-sm text-stone-500">No scheme-funded claimable invoice lines are available for contract resolution.</p>:null}</div></section>;
}
