
drop policy if exists practice_location_manage on public.practice_location;
create policy practice_location_insert on public.practice_location for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_location.practice_id and m.active and m.role in('practice_manager','system_admin')));
create policy practice_location_update on public.practice_location for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_location.practice_id and m.active and m.role in('practice_manager','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_location.practice_id and m.active and m.role in('practice_manager','system_admin')));
create policy practice_location_delete on public.practice_location for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_location.practice_id and m.active and m.role in('practice_manager','system_admin')));

drop policy if exists practitioner_profile_manage on public.practitioner_profile;
create policy practitioner_profile_insert on public.practitioner_profile for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_profile.practice_id and m.active and m.role in('practice_manager','system_admin')));
create policy practitioner_profile_update on public.practitioner_profile for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_profile.practice_id and m.active and m.role in('practice_manager','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_profile.practice_id and m.active and m.role in('practice_manager','system_admin')));
create policy practitioner_profile_delete on public.practitioner_profile for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_profile.practice_id and m.active and m.role in('practice_manager','system_admin')));

drop policy if exists appointment_type_manage on public.appointment_type;
create policy appointment_type_insert on public.appointment_type for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_type.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy appointment_type_update on public.appointment_type for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_type.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_type.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy appointment_type_delete on public.appointment_type for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_type.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));

drop policy if exists practitioner_availability_manage on public.practitioner_availability_rule;
create policy practitioner_availability_insert on public.practitioner_availability_rule for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_availability_rule.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy practitioner_availability_update on public.practitioner_availability_rule for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_availability_rule.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_availability_rule.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy practitioner_availability_delete on public.practitioner_availability_rule for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_availability_rule.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));

drop policy if exists practitioner_schedule_exception_manage on public.practitioner_schedule_exception;
create policy practitioner_schedule_exception_insert on public.practitioner_schedule_exception for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_schedule_exception.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy practitioner_schedule_exception_update on public.practitioner_schedule_exception for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_schedule_exception.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_schedule_exception.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));
create policy practitioner_schedule_exception_delete on public.practitioner_schedule_exception for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practitioner_schedule_exception.practice_id and m.active and m.role in('practice_manager','clinical_admin','system_admin')));

drop policy if exists appointment_waitlist_manage on public.appointment_waitlist;
create policy appointment_waitlist_insert on public.appointment_waitlist for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_waitlist.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));
create policy appointment_waitlist_update on public.appointment_waitlist for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_waitlist.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin'))) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_waitlist.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));
create policy appointment_waitlist_delete on public.appointment_waitlist for delete to authenticated using(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_waitlist.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));

drop policy if exists appointment_request_booking_event_insert on public.appointment_request_event;
create policy appointment_request_booking_event_insert on public.appointment_request_event for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_practice_appointment' and actor_user_id=(select auth.uid()) and exists(select 1 from public.appointment_request r join public.practice_staff_member m on m.practice_id=r.practice_id where r.id=appointment_request_event.appointment_request_id and m.user_id=(select auth.uid()) and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));

drop policy if exists practice_appointment_rpc_insert on public.practice_appointment;
create policy practice_appointment_rpc_insert on public.practice_appointment for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_practice_appointment' and created_by=(select auth.uid()) and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_appointment.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));
drop policy if exists practice_appointment_rpc_update on public.practice_appointment;
create policy practice_appointment_rpc_update on public.practice_appointment for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'') in('/rpc/reschedule_practice_appointment','/rpc/update_practice_appointment_status') and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_appointment.practice_id and m.active)) with check(((select auth.jwt())->>'aal')='aal2' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=practice_appointment.practice_id and m.active));
drop policy if exists appointment_event_rpc_insert on public.appointment_event;
create policy appointment_event_rpc_insert on public.appointment_event for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'') in('/rpc/create_practice_appointment','/rpc/reschedule_practice_appointment','/rpc/update_practice_appointment_status') and actor_user_id=(select auth.uid()) and exists(select 1 from public.practice_appointment a join public.practice_staff_member m on m.practice_id=a.practice_id where a.id=appointment_event.appointment_id and m.user_id=(select auth.uid()) and m.active));
drop policy if exists appointment_sequence_rpc_insert on public.appointment_sequence;
create policy appointment_sequence_rpc_insert on public.appointment_sequence for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_practice_appointment' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_sequence.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin')));
drop policy if exists appointment_sequence_rpc_update on public.appointment_sequence;
create policy appointment_sequence_rpc_update on public.appointment_sequence for update to authenticated using(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_practice_appointment' and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=appointment_sequence.practice_id and m.active and m.role in('reception','practice_manager','clinical_admin','system_admin'))) with check(true);

drop policy if exists billing_invoice_finance_insert on public.billing_invoice;
create policy billing_invoice_finance_insert on public.billing_invoice for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')=any(array['/rpc/create_revenue_invoice','/rpc/convert_billing_quote_to_invoice','/rpc/create_practice_custom_invoice','/rpc/create_encounter_private_invoice']) and created_by=(select auth.uid()) and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=billing_invoice.practice_id and m.active and m.role in('billing','practice_manager','system_admin')));
drop policy if exists billing_quote_insert on public.billing_quote;
create policy billing_quote_insert on public.billing_quote for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_revenue_quote' and created_by=(select auth.uid()) and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=billing_quote.practice_id and m.active and m.role in('billing','practice_manager','system_admin')));
drop policy if exists billing_receipt_finance_insert on public.billing_payment_receipt;
create policy billing_receipt_finance_insert on public.billing_payment_receipt for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')=any(array['/rpc/create_revenue_receipt','/rpc/create_billing_receipt']) and created_by=(select auth.uid()) and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=billing_payment_receipt.practice_id and m.active and m.role in('billing','practice_manager','system_admin')));
drop policy if exists billing_credit_note_insert on public.billing_credit_note;
create policy billing_credit_note_insert on public.billing_credit_note for insert to authenticated with check(((select auth.jwt())->>'aal')='aal2' and coalesce((select current_setting('request.path',true)),'')='/rpc/create_billing_credit_note' and created_by=(select auth.uid()) and exists(select 1 from public.practice_staff_member m where m.user_id=(select auth.uid()) and m.practice_id=billing_credit_note.practice_id and m.active and m.role in('billing','practice_manager','system_admin')));

